### ISSUE TITLE
Approximate with ranges

### ISSUE THREAD

**Issue by barnaclebarnes** [duke-libraries/edtf-humanize#13]
approximate with a range does not work:

Input: `'1946/1950~'`
Actual output: `1946 to 1950`
Expected Output: `1946 to circa. 1950`

```
irb(main):004:0> d = Date.edtf('1946/1950~')
=> #<EDTF::Interval:0x007fb8e66404c8 @from=Tue, 01 Jan 1946, @to=Sun, 01 Jan 1950>
irb(main):005:0> d.humanize
=> "1946 to 1950"
```

**Comment by corylown** [comment]
This looks like it's a straightforward fix.

In the humanize method in the Interval module insert `apply_if_approximate(self.to)` where 'circa' ought to appear when `self.to` is approximate.

I'll get this fix working in a branch and release a new version soon.

Thanks for reporting the issue!

**Comment by corylown** [comment]
@barnaclebarnes a fix for this issue is now in [edtf-humanize v0.0.7](https://rubygems.org/gems/edtf-humanize/versions/0.0.7)
