### ISSUE TITLE
Update?  

### ISSUE THREAD

**Issue by ddavisgraphics** [duke-libraries/edtf-humanize#25]
Are there any plans for an update to get this supported with Rails 6? If not what are your contribution guidelines maybe I could get it working.

**Comment by corylown** [comment]
Good question. I don't have specific plans for adding Rails 6 support (we're not there yet with our Rails apps), but it's likely I could get to this in the next month or two. If you'd like to take a crack at it please feel free to fork it and make a pull request. No contribution guidelines for this other than new features require tests and existing tests should pass.

**Comment by awead** [comment]
Hi all, take a look at https://github.com/duke-libraries/edtf-humanize/pull/26 I may be misunderstanding something, but it looks like you don't need to use Rails to test the gem, unless there are some other test cases I'm missing.

**Comment by corylown** [comment]
Resolved by https://github.com/duke-libraries/edtf-humanize/releases/tag/v1.0.0
